#!/usr/bin/env ruby
puts "compiling tests..."
compres = %x[make tests]
if($? != 0)
  puts "compilation failed"
  puts compres
end
puts ""

failures = []

Dir["bin/*_tests"].each do |file|
  puts "running #{File.basename(file).gsub("_", " ")}"
  puts %x[#{file}]
  puts ""
  if($? != 0)
    failures << file
  end
end

puts "#{failures.size} tests have failed"
failures.each do |file|
  puts "#{File.basename(file).gsub("_", " ")} failed"
end
